services:
  - type: web
    name: pmdd-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_sm"
    startCommand: "uvicorn api.server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: OPENAI_API_KEY
        sync: false
